routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\PostingController;
use App\Http\Controllers\DashboardPromoController;
use Intervention\Image\ImageManagerStatic as Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('test', function() {
    // $documentFiles = Storage::disk("‘tempatfileygakandiupload’")->files(‘\\’);
    //     foreach ($documentFiles as $key => $documentFile){
    //         if ($key == 0) {
    //             $path = Storage::disk(‘tempatfileygakandiupload’)->get($documentFile);
    //             $file_ftp = Storage::disk(‘google’)->put($documentFile, $path);
    //         }
    //     }


    $d=Storage::disk('google')->put('test.txt', 'Hello World');
    // $d=Storage::disk('google')->put('test.txt', 'Hello World');
    dump($d);
    return $d;
});
Route::get('list', function() {
    $dir = '/';
    $recursive = false; // Get subdirectories also?
    $contents = collect(Storage::cloud()->listContents($dir, $recursive));

    //return $contents->where('type', '=', 'dir'); // directories
    return $contents->where('type', '=', 'file'); // files
});
Route::get('list2', function() {
    $img=Image::make('public/90.jpg')->resize(115, 115)->save('public/99.jpg');
    // return $contents->where('type', '=', 'file'); // files
});
// Route::get('/', function () {
//     return view('login');
// });
// Route::get('/', function () { return redirect()->route('dashboard'); });
Route::get('/in', function () { return redirect()->route('dashboard'); })->name('in');
//internal dashboard
Route::get('/loginDashboard', [MainController::class, 'index'])->name('loginDashboard'); //page login
Route::post('/masuk', [MainController::class, 'masuk'])->name('masuk'); //prosses login
Route::get('/daftar', [PendaftaranController::class, 'index'])->name('daftar'); //page register
Route::post('/daftar', [PendaftaranController::class, 'store'])->name('daftar.simpan'); //proses register
Route::get('/logout', [MainController::class, 'logout'])->name('logout'); //proses logout
//public
Route::get('/', [LandingController::class, "index"])->name('home'); //home apps & list posting
Route::get('post', [LandingController::class, "addPost"])->name('posting'); //page create posting
Route::post('search', [LandingController::class, "search"])->name('posting.search'); //page create posting
Route::post('posting', [PostingController::class, "store"])->name('posting.save'); //proses save postingan
Route::get('posting/{id}', [PostingController::class, "show"])->name('posting.detail'); // page detail posting
Route::post('changeActive/{id}',[DashboardPromoController::class,"store"])->name("dashboardPromo.changeActive");
Route::group(['middleware'=>['AuthCheck']], function(){
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    // Route::get('/product', [ProductController::class, 'index'])->name('product');
    // Route::put('/product/{id}', [ProductController::class, 'destroy'])->name('product.delete');
    Route::resource('user',UserController::class);
    Route::resource('dashboardPromo',DashboardPromoController::class);
    Route::resource('product',ProductController::class);
    Route::resource('transaction',TransactionController::class);
    Route::post('/transaction', [TransactionController::class,'index'])->name('transaction.index');
    // Route::get('/transactionrr', [TransactionController::class, 'rr'])->name('rr');
    Route::get('/export', [TransactionController::class,'export'])->name('transaction.export');

    Route::post('/sales/cart', [SalesController::class,'addCart'])->name('sales.addCart');
    Route::get('/sales/reset', [SalesController::class,'reset'])->name('sales.reset');
    Route::get('/print', [SalesController::class,'print']);
    Route::resource('sales',SalesController::class);
});

app/Models/Dashboard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dashboard extends Model
{
    use HasFactory;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dashboard;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
   
    public function index()
    {
        // dd($request->path());
        return view('dashboard.content');
    }

  
    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function show(Dashboard $dashboard)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function edit(Dashboard $dashboard)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dashboard $dashboard)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dashboard $dashboard)
    {
        //
    }
}

resources/views/dashboard/promosmg/index.blade.php
@extends('dashboard.app')
@section('activeMenu')
@php
    $activeMenu="promosmg";
@endphp
@endsection
@section('customLink')
{{-- <link href="{{url('admin/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet"> --}}
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
<style>
    /*Form fields*/
    .dataTables_wrapper select,
    .dataTables_wrapper .dataTables_filter input {
        color: #4a5568; 			/*text-gray-700*/
        padding-left: 1rem; 		/*pl-4*/
        padding-right: 1rem; 		/*pl-4*/
        padding-top: .5rem; 		/*pl-2*/
        padding-bottom: .5rem; 		/*pl-2*/
        line-height: 1.25; 			/*leading-tight*/
        border-width: 2px; 			/*border-2*/
        border-radius: .25rem; 		
        border-color: #edf2f7; 		/*border-gray-200*/
        background-color: #edf2f7; 	/*bg-gray-200*/
    }

    /*Row Hover*/
    table.dataTable.hover tbody tr:hover, table.dataTable.display tbody tr:hover {
        background-color: #ebf4ff;	/*bg-indigo-100*/
    }
    
    /*Pagination Buttons*/
    .dataTables_wrapper .dataTables_paginate .paginate_button		{
        font-weight: 700;				/*font-bold*/
        border-radius: .25rem;			/*rounded*/
        border: 1px solid transparent;	/*border border-transparent*/
    }
    
    /*Pagination Buttons - Current selected */
    .dataTables_wrapper .dataTables_paginate .paginate_button.current	{
        color: #fff !important;				/*text-white*/
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06); 	/*shadow*/
        font-weight: 700;					/*font-bold*/
        border-radius: .25rem;				/*rounded*/
        background: #667eea !important;		/*bg-indigo-500*/
        border: 1px solid transparent;		/*border border-transparent*/
    }

    /*Pagination Buttons - Hover */
    .dataTables_wrapper .dataTables_paginate .paginate_button:hover		{
        color: #fff !important;				/*text-white*/
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);	 /*shadow*/
        font-weight: 700;					/*font-bold*/
        border-radius: .25rem;				/*rounded*/
        background: #667eea !important;		/*bg-indigo-500*/
        border: 1px solid transparent;		/*border border-transparent*/
    }
    
    /*Add padding to bottom border */
    table.dataTable.no-footer {
        border-bottom: 1px solid #e2e8f0;	/*border-b-1 border-gray-300*/
        margin-top: 0.75em;
        margin-bottom: 0.75em;
    }
    
    /*Change colour of responsive icon*/
    table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before, table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
        background-color: #667eea !important; /*bg-indigo-500*/
    }

</style>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
@endsection

@section('pageheading')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Postings</h1>
    {{-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> --}}
</div>
@endsection

@section('script')
<script>

    var datatable=$('#dataTable').DataTable( {
            ajax:{
                url:'{!!url()->current()!!}',
            },
            columnDefs: [{
                            targets: [],
                            render: $.fn.dataTable.render.number( '.', ',', 2)
                        }],
            columns:[
                { data: 'DT_RowIndex', orderable: false, searchable: false },
            {data:'statuss', name:'Statuss',visible: true},
            {data:'tittle', name:'tittle',visible: true},
            {data:'isi', name:'isi',visible: true},
            {data:'no_wa', name:'no_wa',visible: true},
            {data:'act', name:'Act',visible: true},
            {data:'created_at', name:'created_at',visible: true},
            {data:'updated_at', name:'updated_at',visible: true},
            ],
        } );
</script>
@endsection

@section('content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            {{-- <h6 class="m-0 font-weight-bold text-primary ">DataTables Example</h6> --}}
            {{-- <a href="{{route('product.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Add Product</a> --}}
        </div>
        @if (Session::get('fail'))
        {{Session::get('fail')}}
    @endif
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            {{-- <th>Status</th> --}}
                            <th>Status</th>
                            <th>Titlle</th>
                            <th>Isi</th>
                            <th>No Wa</th>
                            <th>Action</th>
                            <th>Create At</th>
                            <th>Active At</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection